### ISSUE TITLE
About the object channel

### ISSUE THREAD

**Issue by AyanamiReiFan** [TonyLianLong/RCF-UnsupVideoSeg#1]
The object channel given in the config file is 1, but after loading the given checkpoint, it is found that the foreground channel is 3. What is the reason?

**Comment by TonyLianLong** [comment]
Object channel differs in each run. The 1 in the config is an example and should be overridden by `--opts object_channel $OBJECT_CHANNEL`, where you set the object channel $OBJECT_CHANNEL with an environment variable. This is given in the examples in README. The object channel can be found without supervision (using our normalized cut metrics).

In your case, if the object channel is 3, you should set the environment variable to 3.

Feel free to ask if you have any questions.

**Comment by AyanamiReiFan** [comment]
Thanks for your reply. Is the filtering of the output channel realized by **_./tools/SemanticConstraintsAndMAA/semantic_constraints.py_** or **_./tools/SemanticConstraintsAndMAA/maa.py_**?

**Comment by TonyLianLong** [comment]
`maa` is motion-appearance alignment, used to find the object channel. An example to use the script is in the readme, section "Stage 2.1".

**Comment by AyanamiReiFan** [comment]
Thanks for your reply.
