### ISSUE TITLE
I hope to obtain the FBMS59 dataset you are using.

### ISSUE THREAD

**Issue by sunsunnyshine** [TonyLianLong/RCF-UnsupVideoSeg#2]
First of all, thank you and your significant contribution to this work!
Here is my small request:
When I wanted to download the FBMS59 dataset, I received a prompt saying 'This section is already in the provider's recycle bin'. I guess you may have accidentally deleted it. SegTrackv2 is still available. If you could recover it from the recycle bin or provide another link(other Drive), I would greatly appreciate it!
If the optical flow is too large, I would like to obtain your resized image dataset
![image](https://github.com/TonyLianLong/RCF-UnsupVideoSeg/assets/87694659/a447746b-0b02-4b9e-86ef-28322a2b7240)

**Comment by TonyLianLong** [comment]
Just restored. Thanks for notifying me about this.

**Comment by sunsunnyshine** [comment]
Sorry to bother you again, the DAVIS2016 optical flow you provided does not include the reverse optical flow ”BackwardFlow“. However, when I generated it using the RAFT official code provided with the **raft thing.pth**, there was a difference between the optical flow results you provided and the one you provided. I noticed that you should have trained on the things and chair datasets. If you could provide the weight pth used in your project, I would greatly appreciate it!

**Comment by TonyLianLong** [comment]
I just checked the `Flows_CT.tgz` and it seems to have `BackwardFlows_NewCT`. Do you mind checking?

**Comment by sunsunnyshine** [comment]
Sorry, the folder was lost while decompressing under ubuntu earlier (for unknown reasons). I have Backwardflow when decompressing under Windows. Thank you for your patience in checking.😀

**Comment by sunsunnyshine** [comment]
Sorry,I found the BackwardFlows_newCT.It's my mistake!
Thank you for your patience in checking.😀
