### ISSUE TITLE
Some question about the  Time consistency

### ISSUE THREAD

**Issue by sunsunnyshine** [TonyLianLong/RCF-UnsupVideoSeg#3]
After reading the appendix of the paper, I found that your method has already implemented consistency constraints on the front and back terms in the residual prediction module. I would like to add the consistency loss between t->t+1 and t->t+2. Have u try this? If you could provide some conclusions after the attempt, it would simplify my work. I would greatly appreciate it!

**Comment by TonyLianLong** [comment]
I haven't tried consistency for more frames. It's possible that it will further boost the results. Feel free to try.

**Comment by sunsunnyshine** [comment]
Thank u for your reply!

**Comment by sunsunnyshine** [comment]
When I conducted experiments on temporal consistency, I found that raft-things.pth performed poorly. However, you have only provided optical flow results for a gap of 1. If you could open-source the weights used in your optical flow prediction section, I believe it would facilitate further research by more scholars building upon your work. Thank you for your patient responses in the past. If it's inconvenient, I appreciate you taking the time to review this request!
